version: '3'

services:
  postgres:
    container_name: devContainer
    image: tobi312/rpi-postgresql
    ports:
      - "5432:5432"
    environment:     
      - POSTGRES_DB=testDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres:/var/lib/postgresql/data -e